// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: valid_hello.proto

package valid_hello

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_HelloRequest_Value = regexp.MustCompile(`^[a-z]{2,5}$`)

func (this *HelloRequest) Validate() error {
	if !_regex_HelloRequest_Value.MatchString(this.Value) {
		return github_com_mwitkow_go_proto_validators.FieldError("Value", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z]{2,5}$"`, this.Value))
	}
	return nil
}

var _regex_HelloResponse_Value = regexp.MustCompile(`^[a-z]{2,5}$`)

func (this *HelloResponse) Validate() error {
	if !(this.Code > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Code", fmt.Errorf(`value '%v' must be greater than '0'`, this.Code))
	}
	if !(this.Code < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("Code", fmt.Errorf(`value '%v' must be less than '100'`, this.Code))
	}
	if !_regex_HelloResponse_Value.MatchString(this.Value) {
		return github_com_mwitkow_go_proto_validators.FieldError("Value", fmt.Errorf(`value '%v' must be a string conforming to regex "^[a-z]{2,5}$"`, this.Value))
	}
	return nil
}
